# Execute CI pipeline using the following global rules:
workflow:
  rules:
    # if it is an MR FROM dev or production, don't run pipeline
    - if: $CI_MERGE_REQUEST_ID && $CI_COMMIT_REF_NAME == "development"
      when: never
    # if it is an MR FROM dev or production, don't run pipeline
    - if: $CI_MERGE_REQUEST_ID && $CI_COMMIT_REF_NAME == "production"
      when: never
    # otherwise, if it is an MR from any other branches, run pipeline
    - if: $CI_MERGE_REQUEST_ID
    # otherwise, if it is not an MR but the branch master, run pipeline
    - if: $CI_COMMIT_REF_NAME == "development" || $CI_COMMIT_REF_NAME == "production"

stages:
  - test
  - deploy

default:
  image: node:14

lint:
  stage: test
  before_script:
    - yarn install
  script:
    - yarn lint

deploy:
  stage: deploy
  rules:
    - if: $CI_COMMIT_REF_NAME == "development"
    - if: $CI_COMMIT_REF_NAME == "production"
  before_script:
    - printf "//registry.npmjs.org/:_authToken=${NPM_CI_TOKEN}\n" > .npmrc
  script:
    - npm publish --access public
