name: Lint
description: Run ESLint
inputs:
  node-version:
    description: Node version to use
    type: string
    required: true
runs:
  using: composite
  steps:
    - uses: actions/setup-node@v3
      with:
        node-version: ${{inputs.node-version}}
        cache: 'yarn'
    - run: yarn install
      shell: bash
    - run: yarn lint
      shell: bash
