const { roundTo, boolToIntString } = require('./utils');
const {
  GCodeFlavors, MachineLimitsUsage,
  InfillPatterns, SolidFillPatterns, SupportPatterns,
  IroningTypes, SeamPositions, BrimTypes,
  DraftShieldModes, FuzzySkinTypes,
  SupportStyles, SupportInterfacePatterns,
} = require('./enums');

class Profile {
  constructor(extruderCount) {
    this.avoidCrossingPerimeters = false;
    this.avoidCrossingPerimetersMaxDetour = 0;
    this.bedCircular = false;
    this.bedSize = [250, 250, 210];
    this.originOffset = [0, 0, 0];
    this.bedTemperature = new Array(extruderCount).fill(0);
    this.beforeLayerGcode = '';
    this.betweenObjectsGcode = '';
    this.bottomFillPattern = SolidFillPatterns.MONOTONIC;
    this.bottomSolidLayers = 4;
    this.bottomSolidMinThickness = 0.5;
    this.bridgeAcceleration = 1000;
    this.bridgeAngle = 0;
    this.bridgeFanSpeed = new Array(extruderCount).fill(100);
    this.bridgeFlowRatio = 0.95;
    this.bridgeSpeed = 30;
    this.brimSeparation = 0.1;
    this.brimType = BrimTypes.NO_BRIM;
    this.brimWidth = 0;
    this.clipMultipartObjects = true;
    this.colorChangeGcode = 'M600';
    this.colorPrintHeights = [];
    this.compatiblePrintersConditionCumulative = '';
    this.completeObjects = false;
    this.cooling = new Array(extruderCount).fill(true);
    this.coolingTubeLength = 0;
    this.coolingTubeRetraction = 0;
    this.defaultAcceleration = 1000;
    this.defaultFilamentProfile = '';
    this.defaultPrintProfile = '';
    this.deretractSpeed = new Array(extruderCount).fill(0);
    this.disableFanFirstLayers = new Array(extruderCount).fill(1);
    this.dontSupportBridges = true;
    this.draftShield = DraftShieldModes.DISABLED;
    this.duplicateDistance = 6;
    this.elephantFootCompensation = 0;
    this.endFilamentGcode = new Array(extruderCount).fill('');
    this.endGcode = '';
    this.ensureVerticalShellThickness = true;
    this.externalPerimeterExtrusionWidth = 0.45;
    this.externalPerimeterSpeed = 25;
    this.externalPerimetersFirst = false;
    this.extraLoadingMove = 0;
    this.extraPerimeters = false;
    this.extruderClearanceHeight = 20;
    this.extruderClearanceRadius = 45;
    this.extruderColor = new Array(extruderCount).fill('#000000');
    this.extruderOffset = new Array(extruderCount).fill(0).map(() => [0, 0]);
    this.extrusionAxis = 'E';
    this.extrusionMultiplier = new Array(extruderCount).fill(1);
    this.extrusionWidth = 0.45;
    this.fanAlwaysOn = new Array(extruderCount).fill(true);
    this.fanBelowLayerTime = new Array(extruderCount).fill(100);
    this.filamentColor = new Array(extruderCount).fill('#000000');
    this.filamentCoolingFinalSpeed = new Array(extruderCount).fill(0);
    this.filamentCoolingInitialSpeed = new Array(extruderCount).fill(0);
    this.filamentCoolingMoves = new Array(extruderCount).fill(0);
    this.filamentCost = new Array(extruderCount).fill(0);
    this.filamentDensity = new Array(extruderCount).fill(1.25);
    this.filamentDeretractSpeed = new Array(extruderCount).fill('nil');
    this.filamentDiameter = new Array(extruderCount).fill(1.75);
    this.filamentLoadTime = new Array(extruderCount).fill(0);
    this.filamentLoadingSpeed = new Array(extruderCount).fill(28);
    this.filamentLoadingSpeedStart = new Array(extruderCount).fill(0);
    this.filamentMaxVolumetricSpeed = new Array(extruderCount).fill(0);
    this.filamentMinimalPurgeOnWipeTower = new Array(extruderCount).fill(0);
    this.filamentNotes = new Array(extruderCount).fill('');
    this.filamentRammingParameters = new Array(extruderCount).fill('');
    this.filamentRetractBeforeTravel = new Array(extruderCount).fill('nil');
    this.filamentRetractBeforeWipe = new Array(extruderCount).fill('nil');
    this.filamentRetractLayerChange = new Array(extruderCount).fill('nil');
    this.filamentRetractLength = new Array(extruderCount).fill('nil');
    this.filamentRetractLift = new Array(extruderCount).fill('nil');
    this.filamentRetractLiftAbove = new Array(extruderCount).fill('nil');
    this.filamentRetractLiftBelow = new Array(extruderCount).fill('nil');
    this.filamentRetractRestartExtra = new Array(extruderCount).fill('nil');
    this.filamentRetractSpeed = new Array(extruderCount).fill('nil');
    this.filamentSettingsId = new Array(extruderCount).fill('Filament');
    this.filamentSoluble = new Array(extruderCount).fill(false);
    this.filamentSpoolWeight = new Array(extruderCount).fill(0);
    this.filamentToolchangeDelay = new Array(extruderCount).fill(0);
    this.filamentType = new Array(extruderCount).fill('PLA');
    this.filamentUnloadTime = new Array(extruderCount).fill(0);
    this.filamentUnloadingSpeed = new Array(extruderCount).fill(0);
    this.filamentUnloadingSpeedStart = new Array(extruderCount).fill(0);
    this.filamentVendor = 'Generic';
    this.filamentWipe = new Array(extruderCount).fill('nil');
    this.fillAngle = 45;
    this.fillDensity = 15;
    this.fillPattern = InfillPatterns.RECTILINEAR;
    this.firstLayerAcceleration = 1000;
    this.firstLayerAccelerationOverRaft = 0;
    this.firstLayerBedTemperature = new Array(extruderCount).fill(0);
    this.firstLayerExtrusionWidth = 0.42;
    this.firstLayerHeight = 0.2;
    this.firstLayerSpeed = 20;
    this.firstLayerSpeedOverRaft = 0;
    this.firstLayerTemperature = new Array(extruderCount).fill(215);
    this.fullFanSpeedLayer = new Array(extruderCount).fill(4);
    this.fuzzySkin = FuzzySkinTypes.NONE;
    this.fuzzySkinPointDistance = 0.8;
    this.fuzzySkinThickness = 0.3;
    this.gapFillEnabled = true;
    this.gapFillSpeed = 40;
    this.gcodeComments = false;
    this.gcodeFlavor = GCodeFlavors.REPRAP_SPRINTER;
    this.gcodeLabelObjects = true; // currently required for Palette postprocessing
    this.gcodeResolution = 0.0125;
    this.highCurrentOnFilamentSwap = false;
    this.hostType = 'octoprint';
    this.infillAcceleration = 1000;
    this.infillAnchor = 2.5;
    this.infillAnchorMax = 12;
    this.infillEveryLayers = 1;
    this.infillExtruder = 1;
    this.infillExtrusionWidth = 0.45;
    this.infillFirst = false;
    this.infillOnlyWhereNeeded = false;
    this.infillOverlap = 25;
    this.infillSpeed = 80;
    this.interfaceShells = false;
    this.ironing = false;
    this.ironingFlowrate = 15;
    this.ironingSpacing = 0.1;
    this.ironingSpeed = 15;
    this.ironingType = IroningTypes.ALL_TOP_SURFACES;
    this.layerGcode = '';
    this.layerHeight = 0.2;
    this.machineLimitsUsage = MachineLimitsUsage.EMIT_TO_GCODE;
    this.machineMaxAccelerationE = [5000, 5000]; // [normal, stealth]
    this.machineMaxAccelerationExtruding = [1250, 1250]; // [normal, stealth]
    this.machineMaxAccelerationRetracting = [1250, 1250]; // [normal, stealth]
    this.machineMaxAccelerationTravel = [1500, 1250]; // [normal, stealth]
    this.machineMaxAccelerationX = [1000, 960]; // [normal, stealth]
    this.machineMaxAccelerationY = [1000, 960]; // [normal, stealth]
    this.machineMaxAccelerationZ = [200, 200]; // [normal, stealth]
    this.machineMaxFeedrateE = [120, 120]; // [normal, stealth]
    this.machineMaxFeedrateX = [200, 100]; // [normal, stealth]
    this.machineMaxFeedrateY = [200, 100]; // [normal, stealth]
    this.machineMaxFeedrateZ = [12, 12]; // [normal, stealth]
    this.machineMaxJerkE = [4.5, 4.5]; // [normal, stealth]
    this.machineMaxJerkX = [8, 8]; // [normal, stealth]
    this.machineMaxJerkY = [8, 8]; // [normal, stealth]
    this.machineMaxJerkZ = [0.4, 0.4]; // [normal, stealth]
    this.machineMinExtrudingRate = [0, 0]; // [normal, stealth]
    this.machineMinTravelRate = [0, 0]; // [normal, stealth]
    this.maxFanSpeed = new Array(extruderCount).fill(100);
    this.maxLayerHeight = new Array(extruderCount).fill(0.25);
    this.maxPrintSpeed = 200;
    this.maxVolumetricSpeed = 0;
    this.minFanSpeed = new Array(extruderCount).fill(100);
    this.minLayerHeight = new Array(extruderCount).fill(0.07);
    this.minPrintSpeed = new Array(extruderCount).fill(15);
    this.minSkirtLength = 4;
    this.mmuSegmentedRegionMaxWidth = 0;
    this.notes = '';
    this.nozzleDiameter = new Array(extruderCount).fill(0.4);
    this.onlyRetractWhenCrossingPerimeters = false;
    this.oozePrevention = false;
    this.outputFilenameFormat = '{input_filename_base}_{layer_height}mm_{filament_type[0]}_{printer_model}_{print_time}.gcode';
    this.overhangs = true; // 'Detect Bridging Perimeters'
    this.parkingPosRetraction = 0;
    this.pausePrintGcode = 'M601';
    this.perimeterAcceleration = 800;
    this.perimeterExtruder = 1;
    this.perimeterExtrusionWidth = 0.45;
    this.perimeterSpeed = 45;
    this.perimeters = 2;
    this.physicalPrinterSettingsId = '';
    this.postProcess = '';
    this.printSettingsId = '';
    this.printerModel = '';
    this.printerNotes = '';
    this.printerSettingsId = '';
    this.printerTechnology = 'FFF';
    this.printerVariant = '';
    this.printerVendor = '';
    this.raftContactDistance = 0.2;
    this.raftExpansion = 1.5;
    this.raftFirstLayerDensity = 90;
    this.raftFirstLayerExpansion = 3;
    this.raftLayers = 0;
    this.remainingTimes = false;
    this.resolution = 0;
    this.retractBeforeTravel = new Array(extruderCount).fill(2);
    this.retractBeforeWipe = new Array(extruderCount).fill(0);
    this.retractLayerChange = new Array(extruderCount).fill(true);
    this.retractLength = new Array(extruderCount).fill(0.8);
    this.retractLengthToolchange = new Array(extruderCount).fill(4);
    this.retractLift = new Array(extruderCount).fill(0.4);
    this.retractLiftAbove = new Array(extruderCount).fill(0);
    this.retractLiftBelow = new Array(extruderCount).fill(209);
    this.retractRestartExtra = new Array(extruderCount).fill(0);
    this.retractRestartExtraToolchange = new Array(extruderCount).fill(0);
    this.retractSpeed = new Array(extruderCount).fill(35);
    this.seamPosition = SeamPositions.NEAREST;
    this.silentMode = false;
    this.singleExtruderMultiMaterial = true;
    this.singleExtruderMultiMaterialPriming = false;
    this.skirtDistance = 2;
    this.skirtHeight = 3;
    this.skirts = 0;
    this.sliceClosingRadius = 0.049;
    this.slicingMode = 'regular';
    this.slowdownBelowLayerTime = new Array(extruderCount).fill(15);
    this.smallPerimeterSpeed = 0;
    this.solidInfillBelowArea = 0;
    this.solidInfillEveryLayers = 0;
    this.solidInfillExtruder = 1;
    this.solidInfillExtrusionWidth = 0.45;
    this.solidInfillSpeed = 80;
    this.spiralVase = false;
    this.standbyTemperatureDelta = -5;
    this.startFilamentGcode = new Array(extruderCount).fill('');
    this.startGcode = '';
    this.supportMaterial = false;
    this.supportMaterialAngle = 0;
    this.supportMaterialAuto = true;
    this.supportMaterialBottomContactDistance = -1; // -1 == use same setting as top interfaces
    this.supportMaterialBottomInterfaceLayers = -1; // -1 == use same setting as top interfaces
    this.supportMaterialBuildplateOnly = false;
    this.supportMaterialClosingRadius = 2;
    this.supportMaterialContactDistance = 0;
    this.supportMaterialEnforceLayers = 0;
    this.supportMaterialExtruder = 0; // 0 == use current extruder
    this.supportMaterialExtrusionWidth = 0.35;
    this.supportMaterialInterfaceContactLoops = false;
    this.supportMaterialInterfaceExtruder = 0; // 0 == use current extruder
    this.supportMaterialInterfaceLayers = 0;
    this.supportMaterialInterfacePattern = SupportInterfacePatterns.RECTILINEAR;
    this.supportMaterialInterfaceSpacing = 0.2;
    this.supportMaterialInterfaceSpeed = 80;
    this.supportMaterialPattern = SupportPatterns.RECTILINEAR;
    this.supportMaterialSpacing = 2;
    this.supportMaterialSpeed = 50;
    this.supportMaterialStyle = SupportStyles.GRID;
    this.supportMaterialSynchronizeLayers = false;
    this.supportMaterialThreshold = 55;
    this.supportMaterialWithSheath = false;
    this.supportMaterialXYSpacing = 50;
    this.temperature = new Array(extruderCount).fill(205);
    this.templateCustomGcode = '';
    this.thickBridges = false;
    this.thinWalls = true;
    this.threads = 20;
    this.thumbnails = [];
    this.toolchangeGcode = '';
    this.topFillPattern = SolidFillPatterns.MONOTONIC;
    this.topInfillExtrusionWidth = 0.4;
    this.topSolidInfillSpeed = 40;
    this.topSolidLayers = 5;
    this.topSolidMinThickness = 0.7;
    this.travelSpeed = 180;
    this.travelSpeedZ = 180;
    this.useFirmwareRetraction = false;
    this.useRelativeEDistances = false;
    this.useVolumetricE = false;
    this.variableLayerHeight = false;
    this.wipe = new Array(extruderCount).fill(false);
    this.wipeIntoInfill = false;
    this.wipeIntoObjects = false;
    this.wipeTower = false;
    this.wipeTowerBridging = 10;
    this.wipeTowerBrimWidth = 2;
    this.wipeTowerNoSparseLayers = false;
    this.wipeTowerRotationAngle = 0;
    this.wipeTowerWidth = 60;
    this.wipeTowerX = 180;
    this.wipeTowerY = 140;
    this.wipingVolumesExtruders = new Array(extruderCount).fill(0).map(() => [70, 70]);
    this.wipingVolumesMatrix = new Array(extruderCount).fill(0).map((_, i) => (
      new Array(extruderCount).fill(0).map((__, j) => (i === j ? 0 : 140))
    ));
    this.xySizeCompensation = 0;
    this.zOffset = 0;

    // not used by PrusaSlicer
    this.clearBufferCommand = 'G4 P0';
    this.towerSpeed = new Array(extruderCount).fill(0);
    this.towerExtrusionWidth = 0.45;
    this.layerGcodePrinterscript = '';
    this.endGcodePrinterscript = '';
    this.startFilamentGcodePrinterscript = new Array(extruderCount).fill('');
    this.startGcodePrinterscript = '';
    this.preSideTransitionPrinterscript = '';
    this.sideTransitionPrinterscript = '';
    this.postSideTransitionPrinterscript = '';
  }

  getBedShapeString() {
    const points = [];
    if (this.bedCircular) {
      // generate 72 points representing the perimeter of circle as a 72-gon
      // (starting at 360 deg / 72, going counter-clockwise, and ending at 0 deg)
      const [diameter] = this.bedSize;
      const [xOff, yOff] = this.originOffset;
      // math explained at https://math.stackexchange.com/a/2547424
      for (let i = 1; i <= 72; i++) {
        const x = Math.cos((2 * Math.PI * i) / 72);
        const y = Math.cos((2 * Math.PI * i) / 72);
        // scale to correct diameter and apply offsets
        points.push([
          roundTo((x * diameter) + xOff, 5),
          roundTo((y * diameter) + yOff, 5),
        ]);
      }
    } else {
      const bottomLeftX = -this.originOffset[0];
      const bottomLeftY = -this.originOffset[1];
      points.push([bottomLeftX, bottomLeftY]);
      points.push([bottomLeftX + this.bedSize[0], bottomLeftY]);
      points.push([bottomLeftX + this.bedSize[0], bottomLeftY + this.bedSize[1]]);
      points.push([bottomLeftX, bottomLeftY + this.bedSize[1]]);
    }
    return points.map(([x, y]) => `${x}x${y}`).join(',');
  }

  toString() {
    const now = new Date();
    const dateString = `${now.getUTCFullYear()}-${now.getUTCMonth() + 1}-${now.getUTCDate()}`;
    const timeString = `${now.getUTCHours()}:${now.getUTCMinutes()}:${now.getUTCSeconds()}`;
    return `; generated by Canvas on ${dateString} at ${timeString} UTC

; avoid_crossing_perimeters = ${boolToIntString(this.avoidCrossingPerimeters)}
; avoid_crossing_perimeters_max_detour = ${this.avoidCrossingPerimetersMaxDetour}
; bed_custom_model =
; bed_custom_texture =
; bed_shape = ${this.getBedShapeString()}
; bed_temperature = ${this.bedTemperature.join(',')}
; before_layer_gcode = ${this.beforeLayerGcode || ';'}
; between_objects_gcode = ${this.betweenObjectsGcode || ';'}
; bottom_fill_pattern = ${this.bottomFillPattern}
; bottom_solid_layers = ${this.bottomSolidLayers}
; bottom_solid_min_thickness = ${this.bottomSolidMinThickness}
; bridge_acceleration = ${this.bridgeAcceleration}
; bridge_angle = ${this.bridgeAngle}
; bridge_fan_speed = ${this.bridgeFanSpeed.join(',')}
; bridge_flow_ratio = ${this.bridgeFlowRatio}
; bridge_speed = ${this.bridgeSpeed}
; brim_separation = ${this.brimSeparation}
; brim_type = ${this.brimType}
; brim_width = ${this.brimWidth}
; clip_multipart_objects = ${boolToIntString(this.clipMultipartObjects)}
; color_change_gcode = ${this.colorChangeGcode || ';'}
; colorprint_heights = ${this.colorPrintHeights.join(',')}
; compatible_printers_condition_cummulative = ${this.compatiblePrintersConditionCumulative}
; complete_objects = ${boolToIntString(this.completeObjects)}
; cooling = ${this.cooling.map(boolToIntString).join(',')}
; cooling_tube_length = ${this.coolingTubeLength}
; cooling_tube_retraction = ${this.coolingTubeRetraction}
; default_acceleration = ${this.defaultAcceleration}
; default_filament_profile = "${this.defaultFilamentProfile}"
; default_print_profile = ${this.defaultPrintProfile}
; deretract_speed = ${this.deretractSpeed.join(',')}
; disable_fan_first_layers = ${this.disableFanFirstLayers.join(',')}
; dont_support_bridges = ${boolToIntString(this.dontSupportBridges)}
; draft_shield = ${this.draftShield}
; duplicate_distance = ${this.duplicateDistance}
; elefant_foot_compensation = ${this.elephantFootCompensation}
; end_filament_gcode = ${this.endFilamentGcode.map(gcode => (gcode ? `"${gcode}"` : '";"')).join(';')}
; end_gcode = ${this.endGcode || ';'}
; ensure_vertical_shell_thickness = ${boolToIntString(this.ensureVerticalShellThickness)}
; external_perimeter_extrusion_width = ${this.externalPerimeterExtrusionWidth}
; external_perimeter_speed = ${this.externalPerimeterSpeed}
; external_perimeters_first = ${boolToIntString(this.externalPerimetersFirst)}
; extra_loading_move = ${this.extraLoadingMove}
; extra_perimeters = ${boolToIntString(this.extraPerimeters)}
; extruder_clearance_height = ${this.extruderClearanceHeight}
; extruder_clearance_radius = ${this.extruderClearanceRadius}
; extruder_colour = ${this.extruderColor.join(';')}
; extruder_offset = ${this.extruderOffset.map(([x, y]) => `${x}x${y}`).join(',')}
; extrusion_axis = ${this.extrusionAxis}
; extrusion_multiplier = ${this.extrusionMultiplier.join(',')}
; extrusion_width = ${this.extrusionWidth}
; fan_always_on = ${this.fanAlwaysOn.map(boolToIntString).join(',')}
; fan_below_layer_time = ${this.fanBelowLayerTime.join(',')}
; filament_colour = ${this.filamentColor.join(';')}
; filament_cooling_final_speed = ${this.filamentCoolingFinalSpeed.join(',')}
; filament_cooling_initial_speed = ${this.filamentCoolingInitialSpeed.join(',')}
; filament_cooling_moves = ${this.filamentCoolingMoves.join(',')}
; filament_cost = ${this.filamentCost.join(',')}
; filament_density = ${this.filamentDensity.join(',')}
; filament_deretract_speed = ${this.filamentDeretractSpeed.join(',')}
; filament_diameter = ${this.filamentDiameter.join(',')}
; filament_load_time = ${this.filamentLoadTime.join(',')}
; filament_loading_speed = ${this.filamentLoadingSpeed.join(',')}
; filament_loading_speed_start = ${this.filamentLoadingSpeedStart.join(',')}
; filament_max_volumetric_speed = ${this.filamentMaxVolumetricSpeed.join(',')}
; filament_minimal_purge_on_wipe_tower = ${this.filamentMinimalPurgeOnWipeTower.join(',')}
; filament_notes = ${this.filamentNotes.join(';')}
; filament_ramming_parameters = ${this.filamentRammingParameters.map(params => `"${params}"`).join(';')}
; filament_retract_before_travel = ${this.filamentRetractBeforeTravel.join(',')}
; filament_retract_before_wipe = ${this.filamentRetractBeforeWipe.join(',')}
; filament_retract_layer_change = ${this.filamentRetractLayerChange.join(',')}
; filament_retract_length = ${this.filamentRetractLength.join(',')}
; filament_retract_lift = ${this.filamentRetractLift.join(',')}
; filament_retract_lift_above = ${this.filamentRetractLiftAbove.join(',')}
; filament_retract_lift_below = ${this.filamentRetractLiftBelow.join(',')}
; filament_retract_restart_extra = ${this.filamentRetractRestartExtra.join(',')}
; filament_retract_speed = ${this.filamentRetractSpeed.join(',')}
; filament_settings_id = ${this.filamentSettingsId.map(val => `"${val}"`).join(';')}
; filament_soluble = ${this.filamentSoluble.map(boolToIntString).join(',')}
; filament_spool_weight = ${this.filamentSpoolWeight.join(',')}
; filament_toolchange_delay = ${this.filamentToolchangeDelay.join(',')}
; filament_type = ${this.filamentType.join(';')}
; filament_unload_time = ${this.filamentUnloadTime.join(',')}
; filament_unloading_speed = ${this.filamentUnloadingSpeed.join(',')}
; filament_unloading_speed_start = ${this.filamentUnloadingSpeedStart.join(',')}
; filament_vendor = ${this.filamentVendor}
; filament_wipe = ${this.filamentWipe.join(',')}
; fill_angle = ${this.fillAngle}
; fill_density = ${this.fillDensity}%
; fill_pattern = ${this.fillPattern}
; first_layer_acceleration = ${this.firstLayerAcceleration}
; first_layer_acceleration_over_raft = ${this.firstLayerAccelerationOverRaft}
; first_layer_bed_temperature = ${this.firstLayerBedTemperature.join(',')}
; first_layer_extrusion_width = ${this.firstLayerExtrusionWidth}
; first_layer_height = ${this.firstLayerHeight}
; first_layer_speed = ${this.firstLayerSpeed}
; first_layer_speed_over_raft = ${this.firstLayerSpeedOverRaft}
; first_layer_temperature = ${this.firstLayerTemperature.join(',')}
; full_fan_speed_layer = ${this.fullFanSpeedLayer.join(',')}
; fuzzy_skin = ${this.fuzzySkin}
; fuzzy_skin_point_dist = ${this.fuzzySkinPointDistance}
; fuzzy_skin_thickness = ${this.fuzzySkinThickness}
; gap_fill_enabled = ${boolToIntString(this.gapFillEnabled)}
; gap_fill_speed = ${this.gapFillSpeed}
; gcode_comments = ${boolToIntString(this.gcodeComments)}
; gcode_flavor = ${this.gcodeFlavor}
; gcode_resolution = ${this.gcodeResolution}
; gcode_label_objects = ${boolToIntString(this.gcodeLabelObjects)}
; high_current_on_filament_swap = ${boolToIntString(this.highCurrentOnFilamentSwap)}
; host_type = ${this.hostType}
; infill_acceleration = ${this.infillAcceleration}
; infill_anchor = ${this.infillAnchor}
; infill_anchor_max = ${this.infillAnchorMax}
; infill_every_layers = ${this.infillEveryLayers}
; infill_extruder = ${this.infillExtruder}
; infill_extrusion_width = ${this.infillExtrusionWidth}
; infill_first = ${boolToIntString(this.infillFirst)}
; infill_only_where_needed = ${boolToIntString(this.infillOnlyWhereNeeded)}
; infill_overlap = ${this.infillOverlap}%
; infill_speed = ${this.infillSpeed}
; interface_shells = ${boolToIntString(this.interfaceShells)}
; ironing = ${boolToIntString(this.ironing)}
; ironing_flowrate = ${this.ironingFlowrate}%
; ironing_spacing = ${this.ironingSpacing}
; ironing_speed = ${this.ironingSpeed}
; ironing_type = ${this.ironingType}
; layer_gcode = ${this.layerGcode || ';'}
; layer_height = ${this.layerHeight}
; machine_limits_usage = ${this.machineLimitsUsage}
; machine_max_acceleration_e = ${this.machineMaxAccelerationE.join(',')}
; machine_max_acceleration_extruding = ${this.machineMaxAccelerationExtruding.join(',')}
; machine_max_acceleration_retracting = ${this.machineMaxAccelerationRetracting.join(',')}
; machine_max_acceleration_travel = ${this.machineMaxAccelerationTravel.join(',')}
; machine_max_acceleration_x = ${this.machineMaxAccelerationX.join(',')}
; machine_max_acceleration_y = ${this.machineMaxAccelerationY.join(',')}
; machine_max_acceleration_z = ${this.machineMaxAccelerationZ.join(',')}
; machine_max_feedrate_e = ${this.machineMaxFeedrateE.join(',')}
; machine_max_feedrate_x = ${this.machineMaxFeedrateX.join(',')}
; machine_max_feedrate_y = ${this.machineMaxFeedrateY.join(',')}
; machine_max_feedrate_z = ${this.machineMaxFeedrateZ.join(',')}
; machine_max_jerk_e = ${this.machineMaxJerkE.join(',')}
; machine_max_jerk_x = ${this.machineMaxJerkX.join(',')}
; machine_max_jerk_y = ${this.machineMaxJerkY.join(',')}
; machine_max_jerk_z = ${this.machineMaxJerkZ.join(',')}
; machine_min_extruding_rate = ${this.machineMinExtrudingRate.join(',')}
; machine_min_travel_rate = ${this.machineMinTravelRate.join(',')}
; max_fan_speed = ${this.maxFanSpeed.join(',')}
; max_layer_height = ${this.maxLayerHeight.join(',')}
; max_print_height = ${this.bedSize[2]}
; max_print_speed = ${this.maxPrintSpeed}
; max_volumetric_speed = ${this.maxVolumetricSpeed}
; min_fan_speed = ${this.minFanSpeed.join(',')}
; min_layer_height = ${this.minLayerHeight.join(',')}
; min_print_speed = ${this.minPrintSpeed.join(',')}
; min_skirt_length = ${this.minSkirtLength}
; mmu_segmented_region_max_width = ${this.mmuSegmentedRegionMaxWidth}
; notes = ${this.notes}
; nozzle_diameter = ${this.nozzleDiameter.join(',')}
; only_retract_when_crossing_perimeters = ${boolToIntString(this.onlyRetractWhenCrossingPerimeters)}
; ooze_prevention = ${boolToIntString(this.oozePrevention)}
; output_filename_format = ${this.outputFilenameFormat}
; overhangs = ${boolToIntString(this.overhangs)}
; parking_pos_retraction = ${this.parkingPosRetraction}
; pause_print_gcode = ${this.pausePrintGcode || ';'}
; perimeter_acceleration = ${this.perimeterAcceleration}
; perimeter_extruder = ${this.perimeterExtruder}
; perimeter_extrusion_width = ${this.perimeterExtrusionWidth}
; perimeter_speed = ${this.perimeterSpeed}
; perimeters = ${this.perimeters}
; physical_printer_settings_id = ${this.physicalPrinterSettingsId}
; post_process = ${this.postProcess}
; print_settings_id = ${this.printSettingsId}
; printer_model = ${this.printerModel}
; printer_notes = ${this.printerNotes}
; printer_settings_id = ${this.printerSettingsId}
; printer_technology = ${this.printerTechnology}
; printer_variant = ${this.printerVariant}
; printer_vendor = ${this.printerVendor}
; raft_contact_distance = ${this.raftContactDistance}
; raft_expansion = ${this.raftExpansion}
; raft_first_layer_density = ${this.raftFirstLayerDensity}%
; raft_first_layer_expansion = ${this.raftFirstLayerExpansion}
; raft_layers = ${this.raftLayers}
; remaining_times = ${boolToIntString(this.remainingTimes)}
; resolution = ${this.resolution}
; retract_before_travel = ${this.retractBeforeTravel.join(',')}
; retract_before_wipe = ${this.retractBeforeWipe.map(val => `${val}%`).join(',')}
; retract_layer_change = ${this.retractLayerChange.map(boolToIntString).join(',')}
; retract_length = ${this.retractLength.join(',')}
; retract_length_toolchange = ${this.retractLengthToolchange.join(',')}
; retract_lift = ${this.retractLift.join(',')}
; retract_lift_above = ${this.retractLiftAbove.join(',')}
; retract_lift_below = ${this.retractLiftBelow.join(',')}
; retract_restart_extra = ${this.retractRestartExtra.join(',')}
; retract_restart_extra_toolchange = ${this.retractRestartExtraToolchange.join(',')}
; retract_speed = ${this.retractSpeed.join(',')}
; seam_position = ${this.seamPosition}
; silent_mode = ${boolToIntString(this.silentMode)}
; single_extruder_multi_material = ${boolToIntString(this.singleExtruderMultiMaterial)}
; single_extruder_multi_material_priming = ${boolToIntString(this.singleExtruderMultiMaterialPriming)}
; skirt_distance = ${this.skirtDistance}
; skirt_height = ${this.skirtHeight}
; skirts = ${this.skirts}
; slice_closing_radius = ${this.sliceClosingRadius}
; slicing_mode = ${this.slicingMode}
; slowdown_below_layer_time = ${this.slowdownBelowLayerTime.join(',')}
; small_perimeter_speed = ${this.smallPerimeterSpeed}
; solid_infill_below_area = ${this.solidInfillBelowArea}
; solid_infill_every_layers = ${this.solidInfillEveryLayers}
; solid_infill_extruder = ${this.solidInfillExtruder}
; solid_infill_extrusion_width = ${this.solidInfillExtrusionWidth}
; solid_infill_speed = ${this.solidInfillSpeed}
; spiral_vase = ${boolToIntString(this.spiralVase)}
; standby_temperature_delta = ${this.standbyTemperatureDelta}
; start_filament_gcode = ${this.startFilamentGcode.map(gcode => (gcode ? `"${gcode}"` : '";"')).join(';')}
; start_gcode = ${this.startGcode || ';'}
; support_material = ${boolToIntString(this.supportMaterial)}
; support_material_angle = ${this.supportMaterialAngle}
; support_material_auto = ${boolToIntString(this.supportMaterialAuto)}
; support_material_bottom_contact_distance = ${this.supportMaterialBottomContactDistance}
; support_material_bottom_interface_layers = ${this.supportMaterialBottomInterfaceLayers}
; support_material_buildplate_only = ${boolToIntString(this.supportMaterialBuildplateOnly)}
; support_material_closing_radius = ${this.supportMaterialClosingRadius}
; support_material_contact_distance = ${this.supportMaterialContactDistance}
; support_material_enforce_layers = ${this.supportMaterialEnforceLayers}
; support_material_extruder = ${this.supportMaterialExtruder}
; support_material_extrusion_width = ${this.supportMaterialExtrusionWidth}
; support_material_interface_contact_loops = ${boolToIntString(this.supportMaterialInterfaceContactLoops)}
; support_material_interface_extruder = ${this.supportMaterialInterfaceExtruder}
; support_material_interface_layers = ${this.supportMaterialInterfaceLayers}
; support_material_interface_pattern = ${this.supportMaterialInterfacePattern}
; support_material_interface_spacing = ${this.supportMaterialInterfaceSpacing}
; support_material_interface_speed = ${this.supportMaterialInterfaceSpeed}%
; support_material_pattern = ${this.supportMaterialPattern}
; support_material_spacing = ${this.supportMaterialSpacing}
; support_material_speed = ${this.supportMaterialSpeed}
; support_material_style = ${this.supportMaterialStyle}
; support_material_synchronize_layers = ${boolToIntString(this.supportMaterialSynchronizeLayers)}
; support_material_threshold = ${this.supportMaterialThreshold}
; support_material_with_sheath = ${boolToIntString(this.supportMaterialWithSheath)}
; support_material_xy_spacing = ${this.supportMaterialXYSpacing}%
; temperature = ${this.temperature.join(',')}
; template_custom_gcode = ${this.templateCustomGcode || ';'}
; thick_bridges = ${boolToIntString(this.thickBridges)}
; thin_walls = ${boolToIntString(this.thinWalls)}
; threads = ${this.threads}
; thumbnails = ${this.thumbnails.map(([x, y]) => `${x}x${y}`).join(',')}
; toolchange_gcode = ${this.toolchangeGcode || ';'}
; top_fill_pattern = ${this.topFillPattern}
; top_infill_extrusion_width = ${this.topInfillExtrusionWidth}
; top_solid_infill_speed = ${this.topSolidInfillSpeed}
; top_solid_layers = ${this.topSolidLayers}
; top_solid_min_thickness = ${this.topSolidMinThickness}
; travel_speed = ${this.travelSpeed}
; travel_speed_z = ${this.travelSpeedZ}
; use_firmware_retraction = ${boolToIntString(this.useFirmwareRetraction)}
; use_relative_e_distances = ${boolToIntString(this.useRelativeEDistances)}
; use_volumetric_e = ${boolToIntString(this.useVolumetricE)}
; variable_layer_height = ${boolToIntString(this.variableLayerHeight)}
; wipe = ${this.wipe.map(boolToIntString).join(',')}
; wipe_into_infill = ${boolToIntString(this.wipeIntoInfill)}
; wipe_into_objects = ${boolToIntString(this.wipeIntoObjects)}
; wipe_tower = ${boolToIntString(this.wipeTower)}
; wipe_tower_bridging = ${this.wipeTowerBridging}
; wipe_tower_brim_width = ${this.wipeTowerBrimWidth}
; wipe_tower_no_sparse_layers = ${boolToIntString(this.wipeTowerNoSparseLayers)}
; wipe_tower_rotation_angle = ${this.wipeTowerRotationAngle}
; wipe_tower_width = ${this.wipeTowerWidth}
; wipe_tower_x = ${this.wipeTowerX}
; wipe_tower_y = ${this.wipeTowerY}
; wiping_volumes_extruders = ${this.wipingVolumesExtruders.map(vals => vals.join(',')).join(',')}
; wiping_volumes_matrix = ${this.wipingVolumesMatrix.map(vals => vals.join(',')).join(',')}
; xy_size_compensation = ${this.xySizeCompensation}
; z_offset = ${this.zOffset}
`;
  }
}

module.exports = Profile;
