name: Build and Deploy

on:
  push:
    branches: ['master']

env:
  NODE_VERSION: 20

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/lint
        with:
          node-version: ${{env.NODE_VERSION}}

  publish:
    name: Publish to NPM
    environment: master
    concurrency: publish
    runs-on: ubuntu-latest
    needs: ['lint']
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: ${{env.NODE_VERSION}}
          registry-url: https://registry.npmjs.org
          cache: 'yarn'
      - run: yarn install --frozen-lockfile
      - run: yarn tsc
      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
