name: PR Workflow

on:
  pull_request:

env:
  NODE_VERSION: 20

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    # if source branch is master, there will already be jobs from
    # the "push" workflow associated with this PR, so nothing needs to be re-run
    if: github.head_ref != 'master'
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/lint
        with:
          node-version: ${{env.NODE_VERSION}}
